export let websites = [
    ['JS Store', 'jsstore.difres.ru'],
    ['DIFRES.RU', 'www.difres.ru'],
    ['Блог разработчика difres.ru', 'blog.difres.ru'],
    ['Разминка.Счёт', 'count.difres.ru'],
    ['Дневник', 'diary.difres.ru'],
    ['Дневник | JS Store', 'jsstore.difres.ru/product?id=1'],
    ['Разминка.Счёт | JS Store', 'jsstore.difres.ru/product?id=2'],
    ['Вопросы и ответы | QnA DIFRES.RU', 'qna.difres.ru'],
    ['Какие команды нужно прописать в консоли для включения bhop на своем сервере CS:GO? | QnA DIFRES.RU', 'qna.difres.ru/question.html?id=1'],
    ['Как открыть диспетчер задач в Windows 10? | QnA DIFRES.RU', 'qna.difres.ru/question.html?id=2'],
    ['Как проще запомнить все цвета радуги? | QnA DIFRES.RU', 'qna.difres.ru/question.html?id=3'],
    ['Как выдать себе нож на своем сервере CS:GO? | QnA DIFRES.RU', 'qna.difres.ru/question.html?id=4'],
    ['GWallpapers | Обои в стиле градиент', 'gradientwallpapers.difres.ru'],
    ['GWallpapers | JS Store', 'jsstore.difres.ru/product.html?id=4'],
    ['Счётчик', 'simplecounter.difres.ru'],
    ['Счётчик | JS Store', 'jsstore.difres.ru/product.html?id=3'],
    ['Как сделать цветной курсор в последних версиях Windows 10? | QnA DIFRES.RU', 'qna.difres.ru/question.html?id=5'],
    ['Как подключить JS-файл к HTML-документу? | QnA DIFRES.RU', 'qna.difres.ru/question.html?id=6'],
    ['DIFRES.RU Видео | Видеохостинг', 'video.difres.ru'],
    ['Главная | Расписание', 'schedule.difres.ru'],
    ['Режим просмотра | Расписание', 'schedule.difres.ru/show.html'],
    ['Экспорт расписания | Расписание', 'schedule.difres.ru/export.html'],
    ['DRK Team Website', 'www.drkteam.ru'],
    ['PhotoStory | Делиться фотографиями с миром', 'photostory.difres.ru']
];